# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('name_book', models.CharField(max_length=100)),
                ('genre_book', models.CharField(default='Жанр неизвестен', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('writer_book', models.CharField(max_length=100)),
                ('year_book', models.DateField()),
                ('number_book', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Book')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
